version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-api-test-jinfei"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-cqdfv7zuvy33"
s3_prefix = "sam-api-test-jinfei"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
